version: '3.7'

services:
  frontend:
    image: artway_frontend
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 125M