name: CI-master

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  UpdateService:
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm -rf /home/user/hack/root-main/frontend
          git clone -b master https://github.com/Zayac11/RT-Hack-2021-RealityX-Frontend.git /home/user/hack/root-main/frontend
          cd /home/user/hack/root-main
          TAG=latest docker-compose -f docker-compose.production.yml build frontend
          docker service update --image rt_frontend:latest main-rt_frontend --force
